"""campos livres do CNJ viram Text

Revision ID: 1027a4b3f12e
Revises: 220224d6c48a
"""
from alembic import op
import sqlalchemy as sa


revision = '1027a4b3f12e'
down_revision = '220224d6c48a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processos', 'orgao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('processos', 'classe',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('publicacoes', 'orgao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('publicacoes', 'classe',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('publicacoes', 'tipo_comunicacao',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('publicacoes', 'tipo_documento',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('publicacoes', 'meio',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('publicacoes', 'ato_inferido',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """ATENÇÃO: este downgrade TRUNCA dados.

    Alargar coluna não é reversível sem perda depois que dado largo entrou. O STJ
    envia frases inteiras em `tipo_documento` onde cabiam 80 caracteres. Sem o
    `USING left(...)` abaixo, o downgrade simplesmente falha com
    StringDataRightTruncationError e a migração fica travada.

    Preferimos truncar EXPLICITAMENTE, com esta nota, a deixar um downgrade que
    não roda — mas confira se você realmente precisa voltar antes de executar.
    """
    op.execute(
        "ALTER TABLE publicacoes ALTER COLUMN orgao TYPE VARCHAR(255) USING left(orgao, 255)"
    )
    op.execute(
        "ALTER TABLE publicacoes ALTER COLUMN classe TYPE VARCHAR(255) USING left(classe, 255)"
    )
    op.execute(
        "ALTER TABLE publicacoes ALTER COLUMN tipo_comunicacao TYPE VARCHAR(80) USING left(tipo_comunicacao, 80)"
    )
    op.execute(
        "ALTER TABLE publicacoes ALTER COLUMN tipo_documento TYPE VARCHAR(80) USING left(tipo_documento, 80)"
    )
    op.execute(
        "ALTER TABLE publicacoes ALTER COLUMN meio TYPE VARCHAR(120) USING left(meio, 120)"
    )
    op.execute(
        "ALTER TABLE processos ALTER COLUMN orgao TYPE VARCHAR(255) USING left(orgao, 255)"
    )
    op.execute(
        "ALTER TABLE processos ALTER COLUMN classe TYPE VARCHAR(255) USING left(classe, 255)"
    )
    op.execute(
        "ALTER TABLE publicacoes ALTER COLUMN ato_inferido TYPE VARCHAR(80) USING left(ato_inferido, 80)"
    )
