"""acervo processual inicial

Revision ID: 220224d6c48a
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '220224d6c48a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos',
    sa.Column('numero_processo', sa.String(length=25), nullable=False),
    sa.Column('numero_formatado', sa.String(length=30), nullable=True),
    sa.Column('tribunal', sa.String(length=12), nullable=False),
    sa.Column('orgao', sa.String(length=255), nullable=True),
    sa.Column('classe', sa.String(length=255), nullable=True),
    sa.Column('polo_do_ente', sa.String(length=20), nullable=False),
    sa.Column('segredo_justica', sa.Boolean(), nullable=False),
    sa.Column('partes_contrarias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('advogados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('numero_processo')
    )
    op.create_index(op.f('ix_processos_tribunal'), 'processos', ['tribunal'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=True),
    sa.Column('entidade_id', sa.String(length=60), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aud_criado', 'auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_auditoria_acao'), 'auditoria', ['acao'], unique=False)
    op.create_table('procuradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('oab_numero', sa.String(length=20), nullable=False),
    sa.Column('oab_uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oab_numero', 'oab_uf', name='uq_oab')
    )
    op.create_index(op.f('ix_procuradores_oab_numero'), 'procuradores', ['oab_numero'], unique=False)
    op.create_table('publicacoes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('numero_processo', sa.String(length=25), nullable=False),
    sa.Column('data_disponibilizacao', sa.Date(), nullable=False),
    sa.Column('tribunal', sa.String(length=12), nullable=False),
    sa.Column('orgao', sa.String(length=255), nullable=True),
    sa.Column('classe', sa.String(length=255), nullable=True),
    sa.Column('tipo_comunicacao', sa.String(length=80), nullable=True),
    sa.Column('tipo_documento', sa.String(length=80), nullable=True),
    sa.Column('meio', sa.String(length=120), nullable=True),
    sa.Column('link_validacao', sa.Text(), nullable=True),
    sa.Column('partes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('advogados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('prazo_no_texto', sa.Integer(), nullable=True),
    sa.Column('ato_inferido', sa.String(length=80), nullable=True),
    sa.Column('rito_inferido', sa.String(length=40), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['numero_processo'], ['processos.numero_processo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pub_data', 'publicacoes', ['data_disponibilizacao'], unique=False)
    op.create_index('ix_pub_venc', 'publicacoes', ['vencimento'], unique=False)
    op.create_index(op.f('ix_publicacoes_numero_processo'), 'publicacoes', ['numero_processo'], unique=False)
    op.create_index(op.f('ix_publicacoes_tribunal'), 'publicacoes', ['tribunal'], unique=False)
    op.create_table('triagem',
    sa.Column('publicacao_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('anotacao', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('publicacao_id')
    )
    op.create_index(op.f('ix_triagem_responsavel_id'), 'triagem', ['responsavel_id'], unique=False)
    op.create_index(op.f('ix_triagem_status'), 'triagem', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triagem_status'), table_name='triagem')
    op.drop_index(op.f('ix_triagem_responsavel_id'), table_name='triagem')
    op.drop_table('triagem')
    op.drop_index(op.f('ix_publicacoes_tribunal'), table_name='publicacoes')
    op.drop_index(op.f('ix_publicacoes_numero_processo'), table_name='publicacoes')
    op.drop_index('ix_pub_venc', table_name='publicacoes')
    op.drop_index('ix_pub_data', table_name='publicacoes')
    op.drop_table('publicacoes')
    op.drop_index(op.f('ix_procuradores_oab_numero'), table_name='procuradores')
    op.drop_table('procuradores')
    op.drop_index(op.f('ix_auditoria_acao'), table_name='auditoria')
    op.drop_index('ix_aud_criado', table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_processos_tribunal'), table_name='processos')
    op.drop_table('processos')
    # ### end Alembic commands ###
